/*Copyright Tim Fleming, Crawford Currie 2014-2025. This file is part of SVGcut, see the copyright and LICENSE at the root of the distribution. */

/* global ClipperLib */

// import "knockout";
/* global ko */
/* global App */

import { ViewModel } from "./ViewModel.js";

import * as Clipper from "./Clipper.js";
import { CamPaths } from "./Cam.js";
import * as Cam from "./Cam.js";

/**
 * @typedef {object} RawPath
 * @property {SnapPath} path path segments
 * @property {boolean} nonzero winding rule
*/

const POPOVERS = [
      { id: "opEnabled" },
      { id: "opOperation" },
      { id: "opCutDepth" },
      { id: "opGenerate" },
      { id: "opName" },
      { id: "opRamp" },
      { id: "opCombine" },
      { id: "opDirection" },
      { id: "opVMaxDepth" },
      { id: "opMargin" },
      { id: "opSpacing" },
      { id: "opWidth" }
];

const FIELDS = [ "name", "enabled", "combineOp", "operation", "cutDepth",
                 "width", "direction", "spacing", "ramp", "margin" ];

/**
 * ViewModel for an operation in the `Operations` card
 */
class OperationViewModel extends ViewModel {

  /**
   * @param {UnitConverter} unit converter to use
   * @param {ClipperLib.Paths} operandPaths input paths to the operation
   */
  constructor(unitConverter, operandPaths) {
    super(unitConverter);

    /**
     * The input to this operation.
     * @member {ClipperLib.Paths}
     * @private
     */
    this.operandPaths = operandPaths;

    /**
     * Geometry generated by combining all the paths in this operation
     * using combineOp.
     * @member {ClipperLib.Paths}
     * @private
     */
    this.combinedGeometry = new ClipperLib.Paths();

    /**
     * SVG showing the geometry for this operation.
     * This is a path that gets added to App.svgGroups.toolPaths
     * @member {SVGGaphicsElement}
     * @private
     */
    this.combinedGeometrySvg = null;

    /**
     * The operation used to combine raw paths to generate the resulting
     * combinedGeometry. One of "Union" (the default), "Intersect", "Diff"
     * or "Xor"
     * @member {observable.<string>}
     */
    this.combineOp = ko.observable("Union");
    this.combineOp.subscribe(() => this.recombine());

    /**
     * The operation type. Default is Engrave as it's simplest.
     * @member {observable.<string>}
     */
    this.operation = ko.observable(App.PolyOps.Engrave);
    this.operation.subscribe(() => this.recombine());

    /**
     * The UI button that opens the detail pane for this operation
     * @member {observable.<button>}
     */
    this.showDetail = ko.observable(false);

    /**
     * The (optional, user provided) name of this operation
     * @member {observable.<string>}
     */
    this.name = ko.observable("");
    this.name.subscribe(() => {
      if (!this.generatingToolpath)
        document.dispatchEvent(new Event("TOOL_PATHS_CHANGED"));
    });

    /**
     * Operations can be selectively enabled/disabled for Gcode
     * generation
     * @member {observable.<boolean>}
     */
    this.enabled = ko.observable(true);
    this.enabled.subscribe(newValue => {
      let v = newValue ? "visible" : "hidden";
      if (this.combinedGeometrySvg)
        this.combinedGeometrySvg.attr("visibility", v);
      if (this.toolPathSvg)
        this.toolPathSvg.attr("visibility", v);
    });
    this.enabled.subscribe(() => {
      if (!this.generatingToolpath)
        document.dispatchEvent(new Event("TOOL_PATHS_CHANGED"));
    });

    /**
     * Enable ramping. See README.md
     * @member {observable.<boolean>}
     */
    this.ramp = ko.observable(false);

    /**
     * Either "Conventional" or "Climb". See README.md
     * @member {observable.<string>}
     */
    this.direction = ko.observable("Conventional");
    this.direction.subscribe(() => this.removeToolPaths());

    /**
     * Paths taken by the tool to execute this operation.
     * @member {observable.<CamPaths>}
     */
    this.toolPaths = ko.observable(new CamPaths());
    this.toolPaths.subscribe(() => {
      if (!this.generatingToolpath)
        document.dispatchEvent(new Event("TOOL_PATHS_CHANGED"));
    });

    /**
     * Svg path generated to show the tool paths. Will be added to
     * the App.svgGroups.toolPaths
     * @member {SVGElement}
     * @private
     */
    this.toolPathSvg = null;

    /**
     * Maximum depth to cut to.
     * @member {observable.<number>}
     */
    this.cutDepth = ko.observable(0);
    unitConverter.add(this.cutDepth);
    this.cutDepth(App.models.Tool.passDepth());

    /**
     * Amount of material to leave uncut.
     * @member {observable.<number>}
     */
    this.margin = ko.observable(0);
    unitConverter.add(this.margin);
    this.margin.subscribe(() => this.recombine());

    /**
     * Amount of material to leave between perforations.
     * @member {observable.<number>}
     */
    this.spacing = ko.observable(0);
    unitConverter.add(this.spacing);
    this.spacing.subscribe(() => this.recombine());

    /**
     * How wide a path to cut. If this is less than the cutter diameter
     * it will be rounded up.
     * @member {observable.<number>}
     */
    this.width = ko.observable(0);
    unitConverter.add(this.width);
    this.width.subscribe(() => this.recombine());

    /**
     * Flag to lock out recombination, usually because we are in a
     * sequence of steps and recombination can wait. See recombine()
     * for more.
     * @member {boolean}
     * @private
     */
    this.disableRecombination = false;

    /**
     * Flag to lock out toolpath generation.
     * @member {boolean}
     * @private
     */
    this.generatingToolpath = false;
  }

  /**
   * @override
   */
  initialise(nodes) {
    this.addPopovers(POPOVERS, nodes);
  }

  /**
   * Toggle the display of the detail dropdown
   */
  toggleDetail() {
    this.showDetail(!this.showDetail());
  }

  /**
   * Remove the geometry contributed by this operation
   */
  removeCombinedGeometry() {
    if (this.combinedGeometrySvg)
      this.combinedGeometrySvg.remove();
    this.combinedGeometrySvg = null;
    this.combinedGeometry = null;
  }

  /**
   * Remove the tool path geometry contributed by this operation
   */
  removeToolPaths() {
    if (this.toolPathSvg)
      this.toolPathSvg.remove();
    this.toolPathSvg = null;
    this.toolPaths(new CamPaths());
  }

  /**
   * Get the width of the path created by the tool as it cuts
   * @return {number} in internal units
   */
  toolPathWidth() {
    const td = App.models.Tool.diameter.toUnits("integer");
    const width = this.width.toUnits("integer");
    if (width < td)
      return td;
    return width;
  }

  /**
   * Invoked from HTML. Operations are bound to this view model, so
   * when removeOperation is bound it comes here.
   */
  removeOperation() {
    App.models.Operations.removeOperation(this);
  }

  /**
   * (Re)generate combinedGeometry from the paths associated with this
   * operation (this.operandPaths) and trigger gCode recompilation
   * @return {boolean} true if recombination was successful
   */
  recombine() {
    if (this.disableRecombination)
      return;

    const opName = this.operation();

    this.removeCombinedGeometry();
    this.removeToolPaths();

    let clipType;
    switch (this.combineOp()) {
    case "Intersect": clipType = ClipperLib.ClipType.ctIntersection; break;
    case "Diff":      clipType = ClipperLib.ClipType.ctDifference; break;
    case "Xor":       clipType = ClipperLib.ClipType.ctXor; break;
    case "Union":
    default:          clipType = ClipperLib.ClipType.ctUnion; break;
    }

    // Merge
    this.combinedGeometry = undefined;
    for (const op of this.operandPaths) {
      this.combinedGeometry = this.combinedGeometry
      ? Clipper.clip(this.combinedGeometry, op, clipType)
      : op;
    }

    let previewGeometry = this.combinedGeometry;

    if (previewGeometry.length > 0) {
      let off = this.margin.toUnits("integer");

      if (opName === App.PolyOps.ConcentricPocket
          || opName === App.PolyOps.Inside)
        off = -off;

      if (opName !== App.PolyOps.Engrave && off !== 0) {
        previewGeometry = Clipper.offset(previewGeometry, off);
      }

      if (opName === App.PolyOps.Inside
          || opName === App.PolyOps.Outside
          || opName === App.PolyOps.Perforate) {
        const width = this.toolPathWidth();
        if (opName === App.PolyOps.Inside)
          previewGeometry = Clipper.diff(
            previewGeometry, Clipper.offset(previewGeometry, -width));
        else // Outside or Perforate
          previewGeometry = Clipper.diff(
            Clipper.offset(previewGeometry, width), previewGeometry);
      }
    }

    if (previewGeometry.length > 0) {
      const svg = Clipper.integer2SVG(previewGeometry);
      if (svg) {
        // Add the new geometry to the global SVG group
        this.combinedGeometrySvg = App.svgGroups.combinedGeometry
        .path(svg)
        .attr("class", "combinedGeometry");
        this.enabled(true);
      }
    }

    this.generateToolPaths();
  }

  /**
   * Generate the tool path(s) for this operation. The tool paths are
   * type CamPath and are written to `this.toolPaths`. Generating toolpaths
   * invalidates Gcode, among other things. An event `TOOL_PATHS_CHANGED` is
   * raised to signal this to the rest of the app.
   */
  generateToolPaths() {
    this.generatingToolpath = true;

    let geometry = this.combinedGeometry;
    const opName = this.operation();
    const toolModel = App.models.Tool;
    const toolDiameter = toolModel.diameter.toUnits("integer");
    const bitAngle = toolModel.angle();
    const passDepth = toolModel.passDepth.toUnits("integer");
    const stepover = toolModel.stepover();
    const climb = (this.direction() === "Climb");
    const zOnTop = App.models.Material.zOrigin() === "Top";
    const cutDepth = this.cutDepth();
    const topZ = zOnTop ? 0 : cutDepth;
    const botZ = zOnTop ? -cutDepth : 0;

    // inset/outset the geometry as dictated by the margin
    let off = this.margin.toUnits("integer");
    if (opName === App.PolyOps.ConcentricPocket
        || opName === App.PolyOps.RasterPocket
        || opName === App.PolyOps.Inside)
      off = -off; // inset
    if (opName !== App.PolyOps.Engrave && off !== 0)
      geometry = Clipper.offset(geometry, off);

    let paths, width;
    switch (opName) {

    case App.PolyOps.ConcentricPocket:
      paths = Cam.concentricPocket(geometry, toolDiameter, 1 - stepover, climb);
      break;

    case App.PolyOps.RasterPocket:
      paths = Cam.rasterPocket(geometry, toolDiameter, 1 - stepover, climb);
      break;

    case App.PolyOps.Inside:
    case App.PolyOps.Outside:
      width = this.width.toUnits("integer");
      if (width < toolDiameter)
        width = toolDiameter;
      paths = Cam.outline(
        geometry, toolDiameter,
        opName === App.PolyOps.Inside, // isInside
        width,
        1 - stepover,
        climb);
      break;

    case App.PolyOps.Perforate:
      paths = Cam.perforate(
        geometry, toolDiameter, this.spacing.toUnits("integer"),
        topZ, botZ);
      break;

    case App.PolyOps.Engrave:
      paths = Cam.engrave(geometry, climb);
      break;
    }

    this.removeToolPaths();
    this.toolPaths(paths);

    // Add the toolpaths to the SVG view
    const spaths = Clipper.integer2SVG(this.toolPaths().integerPaths());
    if (spaths && spaths.length > 0) {
      this.toolPathSvg = App.svgGroups.toolPaths
      .path(spaths)
      .attr("class", "toolPath");
    } else {
      App.showAlert("noToolPaths", "alert-warning", this.name());
    }

    this.enabled(true);
    this.generatingToolpath = false;

    // Signal this change to other listeners
    document.dispatchEvent(new Event("TOOL_PATHS_CHANGED"));
  }

  /**
   * Determine which of the operation fields needs to be enabled for this
   * operation.
   * @param {string} what which field e.g. "width"
   * @return {boolean} true if the field is needed for the current op.
   * @private
   */
  needs(what) {
    const op = this.operation();
    switch (what) {
    case "width": return op === App.PolyOps.Inside
      || op === App.PolyOps.Outside;

    case "direction":
    case "ramp":  return op !== App.PolyOps.Perforate;

    case "margin":  return op !== App.PolyOps.Perforate
      && op !== App.PolyOps.Engrave;

    case "spacing": return op === App.PolyOps.Perforate;
    }
    return true;
  }

  /**
   * @override
   */
  toJson() {
    const json = {
      operandPaths: this.operandPaths
    };

    for (const f of FIELDS)
      if (this.needs(f))
        json[f] = this[f]();

    return json;
  };

  /**
   * @override
   */
  fromJson(json) {
    // suppress recombine until we're finished
    this.disableRecombination = true;

    this.operandPaths = json.operandPaths;
    for (const f of FIELDS)
      this.updateObservable(json, f);

    this.disableRecombination = false;
    this.recombine();
  };
}

export { OperationViewModel }
