/*Copyright Tim Fleming, Crawford Currie 2014-2025. This file is part of SVGcut, see the copyright and LICENSE at the root of the distribution. */
/* global assert */

// import "knockout";
/* global ko */
/* global App */

import { ViewModel } from "./ViewModel.js";

import { CutPath } from "./CutPath.js";
import { CutPaths } from "./CutPaths.js";
import { Rect } from "./Rect.js";
import * as SVG from "./SVG.js";
import * as Cam from "./Cam.js";

const DEFAULT_COMBINEOP = "Union";
const DEFAULT_RAMP = false;
const DEFAULT_DIRECTION = "Conventional";
const DEFAULT_CUTDEPTH = 0;
const DEFAULT_MARGIN = 0;
const DEFAULT_SPACING = 1;
const DEFAULT_SPINDLESPEED = 1000; // rpm
const DEFAULT_WIDTH = 0;

const POPOVERS = [
  { id: "opEnabled" },
  { id: "opOperation" },
  { id: "opCutDepth" },
  { id: "opName" },
  { id: "opRamp" },
  { id: "opCombine" },
  { id: "opDirection" },
  { id: "opVMaxDepth" },
  { id: "opMargin" },
  { id: "opSpacing" },
  { id: "opSpindleSpeed" },
  { id: "opWidth" }
];

const FIELDS = [
  "name", "enabled", "combineOp", "operation", "cutDepth", "width",
  "direction", "spacing", "ramp", "margin", "spindleSpeed"
];

/**
 * ViewModel for an operation in the `Operations` card
 * @listens UPDATE_TOOL_PATHS signal to update all tool paths
 */
class OperationViewModel extends ViewModel {

  /**
   * @param {UnitConverter} unit converter to use
   * @param {CutPaths} operandPaths input paths to the operation
   */
  constructor(unitConverter, operandPaths) {
    super(unitConverter);

    assert(!operandPaths || operandPaths instanceof CutPaths);

    /**
     * The input to this operation.
     * @member {CutPaths}
     * @private
     */
    this.operandPaths = operandPaths;

    /**
     * Geometry generated by combining all the paths in this operation
     * using combineOp.
     * @member {CutPaths}
     * @private
     */
    this.combinedGeometry = new CutPaths();

    /**
     * The combined geometry generated by the operation, in SVG format
     * for adding to #toolPathsSVGGroup. This will be a single path.
     * @member {SVGGaphicsElement}
     * @private
     */
    this.svgPreviewPath = null;

    /**
     * SVG path generated to show the tool paths. Will be added to
     * the #toolPathsSVGGroup element
     * @member {SVGElement}
     * @private
     */
    this.svgToolPath = null;

    /**
     * The operation used to combine raw paths to generate the resulting
     * combinedGeometry. One of "Union" (the default), "Intersect", "Diff"
     * or "Xor"
     * @member {observable.<string>}
     */
    this.combineOp = ko.observable(DEFAULT_COMBINEOP);
    this.combineOp.subscribe(() => this.recombine());
    this.combineOp.subscribe(() => this.projectChanged());

    /**
     * The available operations. This is based on the
     * the mix of open and closed paths in the operandPaths.
     */
    this.availableOperations = ko.observableArray([
      App.Ops.Engrave,
      App.Ops.Perforate,
      App.Ops.Drill
    ]);

    if (operandPaths.filter(p => p.isClosed).length > 0) {
      this.availableOperations.push(
        App.Ops.Inside,
        App.Ops.Outside,
        App.Ops.AnnularPocket,
        App.Ops.RasterPocket);
    }

    /**
     * The operation type. Default is Engrave as it's simplest.
     * @member {observable.<string>}
     */
    this.operation = ko.observable(App.Ops.Engrave);
    this.operation.subscribe(() => this.recombine());
    this.operation.subscribe(() => this.projectChanged());

    /**
     * The UI button that opens the detail pane for this operation
     * @member {observable.<button>}
     */
    this.showDetail = ko.observable(false);

    /**
     * The (optional, user provided) name of this operation
     * @member {observable.<string>}
     */
    this.name = ko.observable("");
    this.name.subscribe(() => this.updateGcode());
    this.name.subscribe(() => this.projectChanged());

    /**
     * Operations can be selectively enabled/disabled for Gcode
     * generation
     * @member {observable.<boolean>}
     */
    this.enabled = ko.observable(true);
    this.enabled.subscribe(newValue => {
      let v = newValue ? "visible" : "hidden";
      if (this.svgPreviewPath)
        this.svgPreviewPath.setAttribute("visibility", v);
      if (this.svgToolPath)
        this.svgToolPath.setAttribute("visibility", v);
    });
    this.enabled.subscribe(() => this.updateGcode());
    this.enabled.subscribe(() => this.projectChanged());

    /**
     * Enable ramping. See README.md
     * @member {observable.<boolean>}
     */
    this.ramp = ko.observable(DEFAULT_RAMP);
    this.ramp.subscribe(() => this.updateGcode());
    this.ramp.subscribe(() => this.projectChanged());

    /**
     * Either "Conventional" or "Climb". See README.md
     * @member {observable.<string>}
     */
    this.direction = ko.observable(DEFAULT_DIRECTION);
    this.direction.subscribe(() => this.generateToolPaths());
    this.direction.subscribe(() => this.projectChanged());

    /**
     * Paths taken by the tool to execute this operation.
     * @member {observable.<CutPaths>}
     */
    this.toolPaths = ko.observable(new CutPaths());
    this.toolPaths.subscribe(() => this.updateGcode());

    /**
     * Maximum depth to cut to.
     * @member {observable.<number>}
     */
    this.cutDepth = ko.observable(DEFAULT_CUTDEPTH);
    unitConverter.add(this.cutDepth);
    this.cutDepth(App.models.Tool.passDepth());
    this.cutDepth.subscribe(() => this.generateToolPaths());
    this.cutDepth.subscribe(() => this.projectChanged());

    /**
     * Amount of material to leave uncut.
     * @member {observable.<number>}
     */
    this.margin = ko.observable(DEFAULT_MARGIN);
    unitConverter.add(this.margin);
    this.margin.subscribe(() => this.recombine());
    this.margin.subscribe(() => this.projectChanged());

    /**
     * Spacing of perforations.
     * @member {observable.<number>}
     */
    this.spacing = ko.observable(DEFAULT_SPACING);
    unitConverter.add(this.spacing);
    this.spacing.subscribe(() => this.recombine());
    this.spacing.subscribe(() => this.projectChanged());

    /**
     * Spindle speed (only one supported)
     * @member {observable.<number>}
     */
    this.spindleSpeed = ko.observable(DEFAULT_SPINDLESPEED);
    this.spindleSpeed.subscribe(
      () => document.dispatchEvent(new Event("UPDATE_GCODE")));
    this.spindleSpeed.subscribe(() => this.projectChanged());

    /**
     * How wide a path to cut. If this is less than the cutter diameter
     * it will be rounded up.
     * @member {observable.<number>}
     */
    this.width = ko.observable(DEFAULT_WIDTH);
    unitConverter.add(this.width);
    this.width.subscribe(() => this.recombine());
    this.width.subscribe(() => this.projectChanged());

    /**
     * Flag to lock out recombination, usually because we are in a
     * sequence of steps and recombination can wait. See recombine()
     * for more.
     * @member {boolean}
     * @private
     */
    this.disableRecombination = false;

    /**
     * Flag to lock out toolpath generation.
     * @member {boolean}
     * @private
     */
    this.generatingToolpath = false;

    document.addEventListener(
      "UPDATE_TOOL_PATHS", () => this.generateToolPaths());
  }

  /**
   * Used internally to signal that toolPaths or Gcode generation
   * parameters have changed.
   * @private
   */
  updateGcode() {
    if (!this.generatingToolpath)
      document.dispatchEvent(new Event("UPDATE_GCODE"));
  }

  /**
   * @override
   */
  initialise(nodes) {
    this.addPopovers(POPOVERS, nodes);
  }

  /**
   * Toggle the display of the detail dropdown.
   * Used from HTML via knockout.
   */
  toggleDetail() {
    this.showDetail(!this.showDetail());
  }

  /**
   * Invoked from HTML. Operations are bound to this view model, so
   * when removeOperation is bound it comes here.
   */
  removeOperation() {
    App.models.Operations.removeOperation(this);
  }

  /**
   * Remove the geometry contributed by this operation
   */
  removeCombinedGeometry() {
    if (this.svgPreviewPath)
      this.svgPreviewPath.remove();
    this.svgPreviewPath = null;
    this.combinedGeometry = null;
  }

  /**
   * Remove the tool path geometry contributed by this operation
   */
  removeToolPaths() {
    if (this.svgToolPath)
      this.svgToolPath.remove();
    this.svgToolPath = null;
    this.toolPaths(new CutPaths());
  }

  /**
   * Get the width of the path to be created by the tool as it cuts.
   * If the user specified width is less than the cutter diameter
   * then it uses the cutter diameter.
   * @return {number} in CutPoint units
   */
  toolPathWidth() {
    const td = App.models.Tool.diameter.toUnits("integer");
    const width = this.width.toUnits("integer");
    if (width < td)
      return td;
    return width;
  }

  /**
   * (Re)generate geometry and tool paths from the paths associated
   * with this operation, by applying the requested combination op
   * (Intersect, Union etc.) The geometry is kept in this.combinedGeometry,
   * and is also added to the combinedGeometry SVG group for preview.
   */
  recombine() {
    if (this.disableRecombination)
      return;

    const oper = this.operation();

    this.removeCombinedGeometry();
    this.removeToolPaths();

    // Combined paths operations are only applied to closed paths
    const closedPaths = this.operandPaths.filter(p => p.isClosed);
    let geom = new CutPaths(closedPaths[0]);

    for (let i = 1; i < closedPaths.length; i++) {
      const others = new CutPaths(closedPaths[i]);
      switch (this.combineOp()) {
      case "Intersect": geom = geom.intersection(others); break;
      case "Diff":      geom = geom.diff(others); break;
      case "Xor":       geom = geom.xor(others); break;
      default:          geom = geom.union(others); break;
      }
    }
    const openPaths = this.operandPaths.filter(p => !p.isClosed);
    for (const op of openPaths)
      geom.push(op);

    this.combinedGeometry = geom;

    let previewGeometry = this.combinedGeometry;

    if (previewGeometry.length > 0) {
      let off = this.margin.toUnits("integer");

      if (oper === App.Ops.AnnularPocket
          || oper === App.Ops.Inside)
        off = -off;

      if (oper !== App.Ops.Engrave && off !== 0)
        previewGeometry = previewGeometry.offset(off);

      if (oper === App.Ops.Inside
          || oper === App.Ops.Outside
          || oper === App.Ops.Perforate
          || oper === App.Ops.Drill) {
        const width = this.toolPathWidth();
        if (oper === App.Ops.Inside) {
          previewGeometry =
            previewGeometry.diff(previewGeometry.offset(-width));
        } else // Outside or Perforate or Drill
          previewGeometry =
            previewGeometry.offset(width).diff(previewGeometry);
      }
    }

    if (previewGeometry.length > 0) {
      const segs = previewGeometry.toSegments();
      if (segs && segs.length > 0) {
        const svgel = document.createElementNS(
          'http://www.w3.org/2000/svg', "path");
        svgel.setAttribute("d", SVG.segments2d(segs));
        svgel.setAttribute("class", "combinedGeometry");
        document.getElementById("combinedGeometrySVGGroup")
        .append(svgel);
        this.svgPreviewPath = svgel;

        this.enabled(true);
      }
    }

    this.generateToolPaths();
  }

  /**
   * (Re)generate the tool path(s) for this operation. The tool paths are
   * kept in `this.toolPaths`. Generating toolpaths invalidates the Gcode,
   * so triggers `UPDATE_GCODE` to signal this.
   */
  generateToolPaths() {
    this.generatingToolpath = true;

    let geometry = this.combinedGeometry;
    const oper = this.operation();
    const toolModel = App.models.Tool;
    const toolDiameter = toolModel.diameter.toUnits("integer");
    const bitAngle = toolModel.angle();
    const passDepth = toolModel.passDepth.toUnits("integer");
    const stepover = toolModel.stepover();
    const climb = (this.direction() === "Climb");
    const zOnTop = App.models.Material.zOrigin() === "Top";
    const cutDepth = this.cutDepth();
    const topZ = zOnTop ? 0 : cutDepth;
    const botZ = zOnTop ? -cutDepth : 0;

    // inset/outset the geometry as dictated by the margin
    let off = this.margin.toUnits("integer");
    if (oper === App.Ops.AnnularPocket
        || oper === App.Ops.RasterPocket
        || oper === App.Ops.Inside)
      off = -off; // inset
    if (oper !== App.Ops.Engrave && off !== 0)
      geometry = geometry.offset(off);

    let paths, width;
    switch (oper) {

    case App.Ops.AnnularPocket:
      paths = Cam.annularPocket(geometry, toolDiameter, 1 - stepover, climb);
      break;

    case App.Ops.RasterPocket:
      paths = Cam.rasterPocket(geometry, toolDiameter, 1 - stepover, climb);
      break;

    case App.Ops.Inside:
    case App.Ops.Outside:
      width = this.width.toUnits("integer");
      if (width < toolDiameter)
        width = toolDiameter;
      paths = Cam.outline(
        geometry, toolDiameter,
        oper === App.Ops.Inside, // isInside
        width,
        1 - stepover,
        climb);
      break;

    case App.Ops.Perforate:
      paths = Cam.perforate(
        geometry, toolDiameter, this.spacing.toUnits("integer"),
        topZ, botZ);
      break;

    case App.Ops.Drill:
      paths = Cam.drill(geometry, topZ, botZ);
      break;

    case App.Ops.Engrave:
      paths = Cam.engrave(geometry, climb);
      break;
    }

    this.removeToolPaths();
    this.toolPaths(paths);

    // Add the toolpaths to the SVG view
    const segs = this.toolPaths().toSegments();
    if (segs && segs.length > 0) {
      const svgel = document.createElementNS(
          'http://www.w3.org/2000/svg', "path");
      svgel.setAttribute("d", SVG.segments2d(segs));
      svgel.setAttribute("class", "toolPath");
      document.getElementById("toolPathsSVGGroup").append(svgel);
      this.svgToolPath = svgel;
    } else {
      App.showAlert("noToolPaths", "alert-warning", this.name());
    }

    this.enabled(true);
    this.generatingToolpath = false;

    // Signal this change to other listeners
    document.dispatchEvent(new Event("UPDATE_GCODE"));
  }

  /**
   * Get the bounding box of the operation in CutPoint units.
   * @return {Rect?} bounding box in Cutpath units. Returns undefined
   * if the operation is not enabled, or doen't generate any paths.
   */
  boundingBox() {
    const paths = this.toolPaths();
    if (!this.enabled() || paths.length === 0)
      return undefined;

    let overlap = 0, BB;
    // Expand the BB if necessary to account for the radius of the
    // tool cutting outside the tool path, Inside and Pocket ops
    // should already have accounted for it.
    const op = this.operation();
    if (op === App.Ops.Engrave)
      overlap = this.toolPathWidth() / 2;
    else if (op === App.Ops.Outside
             || op === App.Ops.Perforate
             || op === App.Ops.Drill)
      overlap = this.toolPathWidth();
    for (const path of paths) {
      for (const point of path) {
        if (BB)
          BB.enclose(point.X - overlap, point.Y - overlap)
          .enclose(point.X + overlap, point.Y + overlap);
        else
          BB = new Rect(point.X - overlap, point.Y - overlap,
                        2 * overlap, 2 * overlap);
      }
    }
    return BB;
  }

  /**
   * Determine which of the operation fields needs to be enabled for this
   * operation.
   * @param {string} what which field e.g. "width"
   * @return {boolean} true if the field is needed for the current op.
   * @private
   */
  needs(what) {
    const op = this.operation();
    switch (what) {
    case "width": return op === App.Ops.Inside
      || op === App.Ops.Outside;

    case "direction":
    case "ramp":  return op !== App.Ops.Perforate
      && op !== App.Ops.Drill;

    case "margin":  return op !== App.Ops.Perforate
      && op !== App.Ops.Drill
      && op !== App.Ops.Engrave;

    case "spacing": return op === App.Ops.Perforate;
    }
    return true;
  }

  /**
   * @override
   */
  toJson() {
    const json = {
      operandPaths: this.operandPaths
    };

    for (const f of FIELDS)
      if (this.needs(f))
        json[f] = this[f]();

    return json;
  };

  /**
   * @override
   */
  fromJson(json) {
    // suppress recombine until we're finished
    this.disableRecombination = true;

    this.operandPaths = json.operandPaths;
    for (const f of FIELDS)
      this.updateObservable(json, f);

    this.disableRecombination = false;
    this.recombine();
  };
}

export { OperationViewModel }
